---
--- Table: SEC_OPER 初始化操作列表，仅包含打印模块，其他业务模块的操作列表应该列在其他初始化数据sql文件中
---
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('0109','载体流转管理','admin',NULL,NULL,'N','Y');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010901','文件流转','admin',NULL,NULL,'N','Y');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01090101','添加流转申请','admin','transfer/viewtransferpaperledger.action','_image/ico/default.gif','N','N');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01090102','查看申请记录','admin','transfer/managepapertransferevent.action','_image/ico/default.gif','N','N');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010902','光盘流转','admin',NULL,NULL,'N','Y');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01090201','添加流转申请','admin','transfer/viewtransfercdledger.action','_image/ico/default.gif','N','N');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01090202','查看申请记录','admin','transfer/managecdtransferevent.action','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010903','流转审批','admin',NULL,NULL,'N','Y');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01090301','待审批列表','admin','basic/manageaprvjob.action?type=TRANSFER','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01090302','查看审批记录','admin','basic/viewaprvjob.action?type=TRANSFER','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010904','接收确认','admin',NULL,NULL,'N','Y');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01090401','载体接收确认','admin','transfer/viewconfirmtransfer.action','_image/ico/default.gif','N','N');

---
--- Table: SEC_ROLE_OPER 配置各角色权限
---
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('10','01090301');
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('10','01090302');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01090101');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01090102');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01090201');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01090202');
---INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01090401');

---
--- Table: SYS_MODULE 系统模块配置
---
INSERT INTO SYS_MODULE(MODULE_CODE,MODULE_NAME) VALUES ('TRANSFER','流转功能模块');
---
--- Table: SEC_CONFIG 设置默认系统配置
---
INSERT INTO SEC_CONFIG(ITEM_KEY,ITEM_NAME,ITEM_VALUE,ITEM_TYPE,STARTUSE) VALUES ('TRANSFER_CONFIRM','流转模块交接确认',null,'CONFIRM',0);