---
--- Table: SEC_ROLE 系统内置角色(role_type=1)，三员角色2,普通角色3，特殊角色4
---
INSERT INTO SEC_ROLE(ROLE_ID,ROLE_NAME,SUBSYS_CODE,ROLE_DESC,ROLE_TYPE,ROLE_SPEC_KEY) 
	VALUES('19','扫描录入管理员','admin','负责外来文件的扫描录入',3,'');
---
--- Table: SEC_OPER 初始化操作列表，仅包含打印模块，其他业务模块的操作列表应该列在其他初始化数据sql文件中
---
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('0106','录入管理','admin',NULL,NULL,'N','Y');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010601','申请录入','admin',NULL,NULL,'N','Y');
---INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060102','提交审批单','admin','enter/submitenterevent.action','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060103','查看申请记录','admin','enter/manageenterlistjob.action','_image/ico/default.gif','N','N');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060104','个人文件录入申请','admin','enter/addpersonalpaperenterevent.action','_image/ico/default.gif','N','N');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060105','个人光盘录入申请','admin','enter/addpersonalcdenterevent.action','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010602','录入审批','admin',NULL,NULL,'N','Y');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060201','待审批列表','admin','enter/manageenteraprvjob.action','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060202','查看审批记录','admin','enter/viewenteraprvjob.action','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010603','载体录入管理','admin',NULL,NULL,'N','Y');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060301','文件录入管理','admin','enter/manageenterpaperlist.action','_image/ico/default.gif','N','N');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060302','光盘录入管理','admin','enter/manageentercdlist.action','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010604','录入记录','admin',NULL,NULL,'N','Y');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060401','文件录入记录','admin','enter/enterpaperhistory.action','_image/ico/default.gif','N','N');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060402','光盘录入记录','admin','enter/entercdhistory.action','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010605','扫描录入申请','admin',NULL,NULL,'N','Y');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060501','申请扫描录入','admin','enter/addscanevent.action','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060502','扫描申请记录','admin','enter/manageenterlistjob.action?entertype=SCAN','_image/ico/default.gif','N','N');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('010606','扫描录入管理','admin',NULL,NULL,'N','Y');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01060601','扫描录入管理','admin','enter/managescanlist.action','_image/ico/default.gif','N','N');
	
---
--- Table: SEC_ROLE_OPER 配置各角色权限
---
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('6','01060301');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('6','01060302');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('6','01060401');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('6','01060402');
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('10','01060201');
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('10','01060202');
---INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01060102');
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01060103');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'PRINT')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01060104');
if exists (select 1 from SYS_MODULE where MODULE_CODE = 'BURN')
	INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01060105');
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01060501');
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01060502');
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('19','01060601');

---
--- Table: SYS_MODULE 系统模块配置
---
INSERT INTO SYS_MODULE(MODULE_CODE,MODULE_NAME) VALUES ('LEADIN','录入功能模块');

--- Table: SEC_CONFIG 交接确认配置
INSERT INTO SEC_CONFIG(ITEM_KEY,ITEM_NAME,ITEM_VALUE,ITEM_TYPE,STARTUSE) VALUES ('ENTER_CONFIRM','录入模块交接确认',null,'CONFIRM',0);
