---
--- Table: SEC_ROLE 系统内置角色(role_type=1)，三员角色2,普通角色3，特殊角色4
---
INSERT INTO SEC_ROLE(ROLE_ID,ROLE_NAME,SUBSYS_CODE,ROLE_DESC,ROLE_TYPE,ROLE_SPEC_KEY) 
	VALUES('8','存储介质管理员','admin','负责硬盘等固定的涉密存储介质的录入、分配、回收等',3,'');

---
--- Table: SEC_OPER 初始化操作列表，仅包含打印模块，其他业务模块的操作列表应该列在其他初始化数据sql文件中
---
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('0110','存储介质管理','admin',NULL,NULL,'N','Y');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('011001','存储介质管理','admin',NULL,NULL,'N','Y');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01100101','存储介质台帐','admin','storage/viewstorage.action','_image/ico/default.gif','N','N');

INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('011105','存储介质台帐','admin',NULL,NULL,'N','Y');
INSERT INTO SEC_OPER(OPER_CODE,OPER_NAME,SUBSYS_CODE,WEB_URL,ICON_PATH,EN_PRVT_OPER,EN_DIRECTORY) VALUES('01110501','存储介质保管台帐','admin','storage/viewselfstorage.action','_image/ico/default.gif','N','N');
																												
---
--- Table: SEC_ROLE_OPER 配置各角色权限
---
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('8','01100101');
INSERT INTO SEC_ROLE_OPER(ROLE_ID,OPER_CODE) VALUES ('11','01110501');
          
---
--- Table: SYS_MODULE 系统模块配置
---
INSERT INTO SYS_MODULE(MODULE_CODE,MODULE_NAME) VALUES ('STORAGE','存储介质功能模块');
---
--- Table: SEC_CONFIG 设置默认系统配置
---
INSERT INTO SEC_CONFIG(ITEM_KEY,ITEM_NAME,ITEM_VALUE,ITEM_TYPE,STARTUSE) VALUES ('STORAGE_BR_CONFIRM','存储介质分配模块交接确认',null,'CONFIRM',0);
INSERT INTO SEC_CONFIG(ITEM_KEY,ITEM_NAME,ITEM_VALUE,ITEM_TYPE,STARTUSE) VALUES ('STORAGE_RT_CONFIRM','存储介质归还模块交接确认',null,'CONFIRM',0);