
package hdsec.web.project.common.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Common", targetNamespace = "http://server.common.project.web.hdsec/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Common {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.common.project.web.hdsec/Common/getMessageRequest", output = "http://server.common.project.web.hdsec/Common/getMessageResponse")
    public String getMessage(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.common.project.web.hdsec/Common/sayHelloRequest", output = "http://server.common.project.web.hdsec/Common/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
